on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: 🚀 Deploy with Fito
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@master

      - name: GO!
        uses: dimaslz/dimaslz-Action@wip2
        with:
          server_ip: ${{ secrets.CONNECTION_HOST }}
          user: ${{ secrets.CONNECTION_USER }}
          ssh_private_key: ${{ secrets.CONNECTION_PRIVATE_KEY }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./b.Dockerfile
          static: true
          app_host: dimaslz.dev
          app_name: node-api
          app_ports: 4000
          env: |
            NODE_ENV=production
            DUMMY=DUMMY DEMO TEXT
            PORT=4000
